### PR TITLE
feat(ui): convert rules to card layout for better readability

### PR DESCRIPTION
**Pull request by lzt1008**
### Description

This PR introduces a new card-style layout for rule descriptions.

The aim is to enhance the readability and visual appeal of the rules.

The changes include a UI overhaul of the rule description section and updated screenshots for comparison.

This PR also includes partial adaptation for mobile, and I can continue to support this in subsequent PRs.

### Linked Issues

- No linked issues as this is a UI enhancement without a prior issue.

### Additional context

The main focus of this PR is the UI change for better clarity when viewing rules. Here are some screenshots for comparison.

Before:
271454257-f386563a-c655-458e-a2c3-0af19ebec958

After:
after
Dark Mode

Before:
Light Mode: Before

After:

Mobile Before:
IMG_0385

Mobile After:
IMG_0387

IMG_0389

### CODE REVIEW

**Comment by antfu** [comment]
Thanks for working on it! I was trying to say I love it but after playing it for a while I kinda have mixed feeling about it.

My main concern is readability. Before this change, the rules were listed linearly, so it was easy to see the relationship between items. I put the status in the front was also to make it easy to read.

But now the default is three columns, which will make you go both up-down and left-right in order to scan all items. The status on the right corn is good at design-wise, but I found it actually becomes harder to grab which rule is enabled and which is not.

For example, here the two rules of `unused-imports/` were meant to be together, but have been wrapped into different rows and columns. 

image

Also here, it becomes less obvious which rule is enabled or not:

image

---

That said, I love the design in general, but I think as such a specific tool, the functionality should have a higher priority than "good looking". I am open for design improvements if you have any other ideas

**Comment by lzt1008** [comment]
Thanks for replying! Yes, the readability of the three-column design is reduced compared to a linear one. Additionally, placing icons on the right side also impacts readability.

My solution is:
Firstly, remove the multi-column layout, maintaining the original single-column design.
Secondly, move the icons from the right to the left side to enhance recognizability. (not sure if this makes it better)

For anything inappropriate, please feel free to make corrections.

Screenshot:
Improved version

**Comment by antfu** [comment]
Yeah, I was already going to push a toggle for grid/list view. But I think with the new design to be the single-column list, it actually takes too much vertical space and wastes the horizontal space. In that case, I'd prefer the original design.

**Comment by lzt1008** [comment]
Thank you for your continued feedback and insights. I understand the concerns regarding space utilization in the single-column layout and the importance of balancing functionality with aesthetics.

The primary intention behind my proposed changes was to address an issue where the description was often too far from the title, making it inconvenient for me to view. I'm not familiar with most of the eslint rule names, so reading descriptions is important to me. By placing the description directly under the title, I aimed to enhance readability. This layout, while it does indeed increase the vertical length and leaves more space on the right (single-column), allows users to keep their visual focus on the left side without having to search for the description on the right. I acknowledge that this approach results in a single-column design, which might not utilize the right-hand space effectively. That said, I am open to suggestions and would be happy to consider alternative designs.

However, at the moment, I really cannot think of a better design or solution that addresses both my pain points and the issues you've raised. Of course, I am willing to continue following up. :)

**Comment by sinh117801** [comment]
Hi everyone, I'd like to add my input here. I'm also experiencing a similar issue with @lzt1008 regarding readability. I think a more readable interface would be helpful. One idea I have is to present the information in a table format, which would not only improve readability but also address @antfu's concern about taking up too much vertical space..

**Pull request closed without merging**
